### ISSUE TITLE
Trying to open facebook.com in a private browsing window closes the window/tab

### ISSUE THREAD

**Issue by pdehaan** [mozilla/contain-facebook#11]
### Steps to reproduce:
1. Git clone.
1. `web-ext run -s .` to launch w/ a fresh Firefox and add-on preinstalled.
1. File ➡️ New Private Window.
1. Go to "facebook.com" (tab auto closes, also, so does the private browser instance, since it was the only open tab).
1. File ➡️ New Private Window.
1. Go to "bing.com" (or whatever, who cares)
1. Open a new/second tab, and go to "facebook.com" (tab auto closes, but window remains open since we had a second open tab).

### Actual results:
I seemingly cannot launch Facebook in a Private Window without it auto-closing.

### Expected results:
I honestly have no clue. But this doesn't feel like the correct behavior.

---

![tp-facebook](https://user-images.githubusercontent.com/557895/37741856-58bda8dc-2d20-11e8-9662-7b3e7e66b2db.gif)

**Comment by elvey** [comment]
Yes we should note that somewhere prominent.   (Why: I almost opened a new bug because I created another container for a second facebook login, and it wouldn't work.  I'm not opening a new bug - because I managed to find this one first - and thereby discovered that one can still use private browsing to access facebook with a different login. So the ability to allow one to "Log in to multiple accounts on a single website at the same time" that containers gives you isn't broken by this extension. :-) ). Lets note it somewhere prominent.
