### ISSUE TITLE
Tab history is lost when openng 

### ISSUE THREAD

**Issue by Matt3o12** [mozilla/contain-facebook#143]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? No
- Are you using Firefox in a Private Window? No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes (ticked)
- Facebook Container Version: 1.3.1
- Operating System + Version: MacOS 10.13.4 (also applies to Xubuntu but I'm not sure which version)
- Firefox Version: 59.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:

 Name
Version 	Enabled 	ID
1Password Beta	4.7.1.3	true	onepassword4@agilebits.com
ADB Helper	0.12.0	true	adbhelper@mozilla.org
Facebook Container	1.3.1	true	@contain-facebook
Modify Header Value (HTTP Headers)	0.1.3	true	jid0-oEwF5ZcskGhjFv4Kk4lYc@jetpack
QR Code Generator	3.0.0	true	jid0-RwTySlpoKU14fw7yw2AflOAihhA@jetpack
uBlock Origin	1.15.24	true	uBlock0@raymondhill.net
Vimium	1.63.3	true	{d7742d87-e61d-4b78-b8a1-b469842139fa}
Graphics 

### Actual/Expected behavior

When clicking any link that refers to facebook/instergram/etc the tab history is lost. It should be possible to open a facebook tab and still be able to go back (and use a normal tab as soon as you go back). If this is technically not possible, there should be an option that always opens facebook links in another tab (if there is an option, I'm sorry I wasn't able to find it). It is not practical to do that manually because:
  
  1) facebook links are sometimes hidden behind bit.ly, etc and you cannot identify the link as such.
  2) You sometimes just forget that you are about to open a facebook link and finding the previous pages again can be tedious
 3) Normal users can get annoyed at that and simply disable contain-facebook because of that.

### Steps to reproduce
1. Go to some websites which eventually lead to a link to facebook
2. Click on that facebook link
3. Try to find the pages you visited in 1) again.

**Comment by irgendsontyp** [comment]
Any chances this will be changed in some way? Not being able to navigate back to the previous page after going to facebook is very annoying to me. I'd be very glad if this was possible.

**Comment by finnoleary** [comment]
I have exactly the same problem still. Same settings as well.

**Comment by ygoe** [comment]
I regularly find Facebook or other sites in Google that will open in a container tab. But I'm used to be able to go back to the search and open another result. This badly fails now with the Facebook container.

Is there at least a way to force-open new containers a *additional tab* instead of *replacing*? It's not uncommon that links open in a new tab at their own will, so that would at least be a well-known behaviour and preserve the previous history. The current state is much worse than that.

Since this issue is scheduled for a milestone without time schedule and the previous milestone is already long overdue (is this project even still active?! after all it's a top recommendation from Mozilla), a workaround in a soon release would be much appreciated.

**Comment by finnoleary** [comment]
I mean, I get how the code is structured means that it's probably difficult or impossible to do container tabs any other way as-is. But I feel like somewhere in the platonic space there is another implementation that turns the container on when you visit that site, and doesn't communicate prior session information outside the container environment, to the application.

**Comment by ygoe** [comment]
I assume that this line needs to be removed:

https://github.com/mozilla/contain-facebook/blob/7bded6672ece630166078dbf31663ac7cf0825fc/src/background.js#L266

I cannot test it because Firefox is so badly locked down now that I cannot even patch that extension and verify my fix. It won't load the new extension, even with XPI signing disabled. Firefox is not a developer browser anymore. I wonder how I should develop my own extensions when everything has to be digested (inspected and signed) by the Mozilla Central Authority first?

**Comment by maxxcrawford** [comment]
@ygoe You should be able to run the extension locally through [web-ext](https://github.com/mozilla/web-ext). We also have a [development guide](https://github.com/mozilla/contain-facebook#development) in this repo.

**Comment by addeps3** [comment]
I would prefer the extension to open contained links in a new tab, instead of closing the previous one, because when I click results after googling them, and the search tab closes, I have repeat the search, or re-open the previously closed tab. 
It would be much more convenient to just open a new tab when clicking contained links. 
Or let the user select behavior.

**Comment by shbach** [comment]
This looks like a duplicate of #24. Clearly, this is an issue that keeps getting reported for the past two years without a fix.

**Comment by addeps3** [comment]
@shbach 
I tested again, now that I recieved your notice.
On FF 76.0.1 it is working.

**Comment by maxxcrawford** [comment]
Duplicate of #24

**Comment by addeps3** [comment]
...And stopped working again.
