### ISSUE TITLE
?fbclid is being used to escape the container

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/contain-facebook#178]
Facebook has introduced a new `?fbclid=...` URL parameter that is appended to all outbound links. This sidesteps third-party cookie restrictions and permits associating someone's Container instance with their non-Container instance.

**Comment by TanviHacks** [comment]
What would be the consequence of stripping fbclid whenever we switch out of the facebook container into another one?

Do we need to consider stripping it from facebook.com links too?  So that if we are in some other container and about to open a facebook link in the facebook container, we don't include that parameter, in case it is used to link activity that happened in the previous container?

**Comment by groovecoder** [comment]
There should be no problem stripping `fbclid` from the urls before entering or leaving the FB container.

**Comment by d-alleyne** [comment]
Is there a way to get this code without waiting for AMO to update?

**Comment by groovecoder** [comment]
Not easily. But I'll plan to update AMO tomorrow.
