### ISSUE TITLE
Add FB Container logo as a Container icon

### ISSUE THREAD

**Issue by groovecoder** [mozilla/contain-facebook#205]
We would like to use the FB Container logo as the container icon, rather than the briefcase.

@jonathanKingston should be able to provide links to the MAC privileged code that added icons, and/or the bug that added the icons to platform.

**Comment by jonathanKingston** [comment]
Some commit links:
https://github.com/mozilla/multi-account-containers/commit/04720de11ece4cd136d42ec76f1cf5bb6b569af1
https://github.com/mozilla/multi-account-containers/commit/364d911f724fad56d6a14f506980c3d707d8bcbc

FX change to add new icons:
https://bugzilla.mozilla.org/show_bug.cgi?id=1387003

Mozilla central code:
https://searchfox.org/mozilla-central/rev/dc0adc07db3df9431a0876156f50c65d580010cb/browser/components/contextualidentity/content/usercontext.css#41

The code has changed in central slightly since the icons were in MAC however the change would require a browser experiment to change the icon in the URL bar, you would essentially be injecting in CSS or JS that overrode this: https://searchfox.org/mozilla-central/rev/dc0adc07db3df9431a0876156f50c65d580010cb/browser/components/contextualidentity/content/usercontext.css#113-123

I can be assistance more whenever this is being implemented.

**Comment by groovecoder** [comment]
@jonathanKingston we've done our user testing and have decided to add the facebook container fence icon as the icon for the container.

To get it in time for a 4/29 release, it sounds like we'll have to add it with privileged browser experiment code. (If we patch central **and** uplift to beta, it still won't be available in release until May 14)

Is that something you can help us with?

**Comment by jonathanKingston** [comment]
@groovecoder do you have the chosen icon available (is it still the one attached in: https://bugzilla.mozilla.org/show_bug.cgi?id=1532746)?

> To get it in time for a 4/29 release, it sounds like we'll have to add it with privileged browser experiment code. (If we patch central and uplift to beta, it still won't be available in release until May 14)

As for making it work in the addon, it likely will have to run an update in the addon to the icon and then catch an exception for a non supporting 'fence' icon in stable and then inject UI code into the browser CSS.

As mentioned previously the OSX bar will likely have issues with it being the wrong icon as it's not styleable by the same CSS.

I would like to land 1532746 this after https://bugzilla.mozilla.org/show_bug.cgi?id=1479433 which should be upliftable also.

**Comment by groovecoder** [comment]
I submitted https://phabricator.services.mozilla.com/D26988 to get the gray color + fence icon into central ASAP.
