### ISSUE TITLE
The Facebook website is wrongly moved between its assigned container and the "Facebook" container tab in a continuous loop

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/contain-facebook#23]
**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Multi-Account Containers" add-on (6.0.0) installed from https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/?src=search.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and open a new container (eg. Personal).
2. Navigate to "https://www.facebook.com/" in the container from step 1. 
3. Click the "Multi-Account Containers" toolbar button and check the "Always Open in Personal" option.
4. Navigate to the "about:debugging" page and load the "Facebook Container" add-on (1.1.0) as temporary add-on.
5. Open a new normal tab and navigate to "https://www.facebook.com/".
6. Check the "Remember my decision for this site" option when prompted and click the "Open in Personal Container" button.
7. Observe the behavior.

**[Expected result]:**
- The "https://www.facebook.com/" website is opened in the "Personal" container.

**[Actual result]:**
- The https://www.facebook.com/ website is moved between the "Personal" and the "Facebook" container tab in a continuous loop.

**[Notes]:**
- The issue is also reproducible if the "Facebook" website is assigned to any other container instead of the "Personal" one.
- Attached a screen recording of the issue: 
![loop between containers](https://user-images.githubusercontent.com/17258026/37773505-74b0fee2-2de6-11e8-945b-caffdf15ae00.gif)

**Comment by SoftVision-PaulOiegas** [comment]
Sadly, it seems that this is reproducing after a browser restart. We couldn't have caught this without the signed XPI because it requires restarting the browser and we didn't had it until 20 minutes before it was released. 

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and open a new container (eg. Personal).
2. Navigate to "https://www.facebook.com/" in the container from step 1. 
3. Click the "Multi-Account Containers" toolbar button and check the "Always Open in Personal" option.
4. Install the Facebook Container add-on from AMO and restart the browser.
5. Open a new normal tab and navigate to "https://www.facebook.com/".
6. Check the "Remember my decision for this site" option when prompted and click the "Open in Personal Container" button.

**Comment by groovecoder** [comment]
Got it. Looks like this add-on is checking for an assignment before the `@testpilot-containers` add-on is fully loaded.

**Comment by SoftVision-PaulOiegas** [comment]
@groovecoder  just making sure that this was the desired behavior. 

After doing all the above steps, when prompted on which tab FB should open, you check the remember option and choose the "Open in Personal" container. Then the FB page is opened in the "Personal" one and not in the Facebook Container that was created by our add-on.

**Comment by stoically** [comment]
The fix in #47 doesn't completely address this. The additional call to `management.get` might delay execution enough that, while testing, MAC is fast enough with initializing to answer the `runtime.sendMessage`, however, it doesn't guarantee complete initialization of MAC. One way to make it reliable would be to enter a loop if `runtime.sendMessage` throws because of "receiving end doesn't exist" and wait until `runtime.sendMessage` doesn't throw anymore (which implicitly means that MAC is fully initialized).

Also, if an user installs MAC after installing contain-facebook and then assigns facebook to "Always open in", the same issue will arise. Same goes for users that already have MAC installed and change the "Always open in" assignment for facebook after contain-facebook got initialized (which is after install, browser start or disable/enable).

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible using Facebook Container (v1.2.5) on latest Firefox Release 59.0.2. Tested on Windows 7 x64, Mac 10.13.3 and Ubuntu 14.04 x64. 

I have tested this issue using multiple scenarios that also includes the ones described by @stoically  in the above comment and I haven't encountered any issues during testing.

**Comment by wellington1993** [comment]
HI!

Has that error any relation?
`JavaScript error: moz-extension://0e34cc0f-daaf-4976-a261-e73661f81f77/background.js, line 503: Error: Could not establish connection. Receiving end does not exist.
`
Sorry if the error doesn't have any relation., because the issue search suggested this issue.

Thanks!

**Comment by maxxcrawford** [comment]
@wellington1993 Are you getting the same loop assignment?

**Comment by wellington1993** [comment]
@maxxcrawford Sometimes I have the same problem.... Same loop.

**Comment by wellington1993** [comment]
@maxxcrawford But I think is not occurred anymore in last updates.

**Comment by Haaroon** [comment]
this issue seems to persist with the latest container plugin (as of 3rd Jan 19) and firefox 71
