### ISSUE TITLE
Facebook Workplace's new domain

### ISSUE THREAD

**Issue by boricic** [mozilla/contain-facebook#241]
Facebook's [Workplace](https://www.facebook.com/workplace) product was sharing the domain with Facebook itself up until recently.

Currently they are migrating to their own domain `workplace.com`.

Since Facebook Workplace is practically the same code base as Facebook itself, I imaging all tracking features of Facebook are present in the Workplace too.

I suggest we add new `workplace.com` domain to the list of domains that are put inside Facebook Container.

If you agree I can even make the PR.

**Comment by groovecoder** [comment]
Thanks for the contribution. We are conducting some site audits now, and we will have make an effort to combine GitHub domain requests with domain lists from Disconnect and from other data-sets to come up with an expanded domain list to include in a single new release all at once.

I'm closing this PR for now, but labeling it with `domain-request` so we can look at all issues and PRs with that label when we expand our domain containment list.

**Comment by R-Adrian** [comment]
I need this for Workplace too... i have both the Facebook container and the Multi-account-containers addons ( https://github.com/mozilla/multi-account-containers ) and when both are enabled i cannot force the site to be loaded in the Facebook container.

The current version of the Facebook Container addon that's published on addons.mozilla.org (v1.6.5) does not allow me to force loading the domain **workplace.com** in a Facebook container, i tried using either of these addons, the list of sites that are members in the Facebook container seems to be read-only, i cannot force a website to open in the Facebook container :(

**Comment by Howshall** [comment]
Confirm I also need Workplace by Facebook domain https://www.workplace.com/ adding to default Facebook owned domains list. As currently I also can't find any way to manually add that site to the domains automatically opened by Facebook Container Addon within Facebook container tab.

**Comment by Jinstarro** [comment]
Same. I have to disable Facebook Container when using Workplace. Hopefully they'll add it soon.

**Comment by passcod** [comment]
Just to add to this, it is not just that workplace is another facebook domain, it's that because of how workplace is served, this addon currently _completely and utterly breaks workplace.com_ until it's disabled, therefore forcing to choose between having a functional workplace or privacy.

**Comment by maxxcrawford** [comment]
@passcod @Jinstarro @Howshall @R-Adrian @boricic 

I created a PR adding the work place domain to the Facebook Container. Please [try out](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Distribution_options/Sideloading_add-ons#Using_Install_Add-on_From_File) the PR to see if this resolves your issue. 

I added the following domains: 
 
- workplace.com
- www.workplace.com
- work.facebook.com 

.zip of PR #459: 
+ https://send.firefox.com/download/26f42108e4ebbd14/#q9ptmTfz5G6NpodttmmmXQ

**Comment by passcod** [comment]
Works great

**Comment by Howshall** [comment]
While addon change to add workplace.com domains to Facebook container auto URLs now means initial homepage renders correctly for me. My company uses Microsoft for single sign-on to Workplace, so with latest Add-on initial workplace.com homepage now works and renders correctly, BUT because I then get send across to Microsoft signin https://login.microsoftonline.com/ (where Facebook Container understandably reverts to normal tab). However that means on return from successful MS signin the addon triggers back into Facebook Container for https://bt.workplace.com/work/saml.php but that container doesn't have my MS login details token (as they were done outside of FB container switch)

At the moment I therefore still can't login successfully to my company's Workplace by Facebook as attempting to manually force MS signin page to happen within Facebook Container via right click 'Reopen in container > Facebook' is broken. As I've reported separately as https://github.com/mozilla/contain-facebook/issues/457
