### ISSUE TITLE
The badge for share buttons is not always displayed for certain websites

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/contain-facebook#341]
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
 - Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the latest [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**
1. Go to https://www.football.london/tottenham-hotspur-fc/fixtures-results/spurs-press-conference-live-mauricio-16255596
2. Inspect the Facebook share button.

**Expected result:**
- The Facebook share button has the badge properly displayed.

**Actual result:**
- The Facebook share button has no badge displayed.

**Notes:**
- Other websites affected by this issue: https://www.skysports.com/football/news/11667/11715959/manchester-united-to-close-agreeing-daniel-james-deal-from-swansea
- https://imgur.com/gallery/sPC8df5
- Please see the attached screenshot
![Screenshot from 2019-05-10 17-05-13](https://user-images.githubusercontent.com/43886441/57533184-d54c5d00-7345-11e9-8c7f-d98de609b660.png)
 with the issue:

**Comment by obotisan** [comment]
We found other sites that this bug is reproducing on:
- [amazon jp](https://www.amazon.co.jp/%E5%B1%B1%E5%96%84-YAMAZEN-%E3%83%AA%E3%83%93%E3%83%B3%E3%82%B0%E6%89%87%E9%A2%A8%E6%A9%9F/dp/B07NJNL8PC?pd_rd_wg=9uLIG&pd_rd_r=3650514f-fc9f-4884-9fa7-6bbcab7d5176&pd_rd_w=o5VoL&ref_=pd_gw_ri&pf_rd_r=FWK5G2T4XVHBPZQ8T40V&pf_rd_p=4118aba8-c3ed-58bb-a9ce-c4054503fac6https://www.amazon.co.jp/%E5%B1%B1%E5%96%84-YAMAZEN-%E3%83%AA%E3%83%93%E3%83%B3%E3%82%B0%E6%89%87%E9%A2%A8%E6%A9%9F/dp/B07NJNL8PC?pd_rd_wg=9uLIG&pd_rd_r=3650514f-fc9f-4884-9fa7-6bbcab7d5176&pd_rd_w=o5VoL&ref_=pd_gw_ri&pf_rd_r=FWK5G2T4XVHBPZQ8T40V&pf_rd_p=4118aba8-c3ed-58bb-a9ce-c4054503fac6https://www.amazon.co.jp/%E5%B1%B1%E5%96%84-YAMAZEN-%E3%83%AA%E3%83%93%E3%83%B3%E3%82%B0%E6%89%87%E9%A2%A8%E6%A9%9F/dp/B07NJNL8PC?pd_rd_wg=9uLIG&pd_rd_r=3650514f-fc9f-4884-9fa7-6bbcab7d5176&pd_rd_w=o5VoL&ref_=pd_gw_ri&pf_rd_r=FWK5G2T4XVHBPZQ8T40V&pf_rd_p=4118aba8-c3ed-58bb-a9ce-c4054503fac6)
- https://www.quora.com/
- [nbc sports](https://profootballtalk.nbcsports.com/2019/05/13/ej-manuel-geno-smith-moves-a-reminder-of-the-weak-2013-draft-class/)

You can find other examples by using [this link](https://docs.google.com/spreadsheets/d/1XxaKZjKPNSHyT3hr1D0TYHU6XhsN54U4-VXm8Mj1fbQ/edit#gid=0). Do we need to log issues separately for each site?
