### ISSUE TITLE
No menu or panels on browserAction in Italian build

### ISSUE THREAD

**Issue by flodolo** [mozilla/contain-facebook#355]
Testing the add-on built on master (package version is 1.7.1). There are no actions associated to the toolbar icon, it's gray and completely inactive.

**Comment by groovecoder** [comment]
@flodolo  ah, I think I found it. my 100% check returned false if any of the locale’s messages were the same as `en`. And one of the messages is `facebookContainer` - the name of the extension. So since that’s not translated, it’s returning `false`.

I can either fix the check to ignore that particular message, or I can remove the check completely. What do you think is best?
