### ISSUE TITLE
Duplicate share button badges occuring on Imgur.com 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/contain-facebook#389]
## Issue

Duplicate badges are being drawn/assigned on a page with one share button. 

_Originally posted by @g3rain1 in https://github.com/mozilla/contain-facebook/issues/387#issuecomment-494956180_

## Screenshots

https://i.imgur.com/PsXt8lF.jpg

![image](https://user-images.githubusercontent.com/2692333/58206170-d1093380-7ca5-11e9-8d84-b6fc42cfbc80.png)

![image](https://user-images.githubusercontent.com/2692333/58206179-d36b8d80-7ca5-11e9-911c-cadefc869849.png)

**Comment by DOFandersolsen** [comment]
This might be a better example of whats happening:
![billede](https://user-images.githubusercontent.com/16536056/58404328-2dcd6b00-8065-11e9-88b0-1d734a26b34c.png)

Imgur acts as a Single-Page Application, so whenever the user navigates to a new picture, the site itself is not refreshed, however the Facebook button is moved because the size of the images vary, so a new fence-button is made at the new spot of the Facebook button, but the old fences are not removed because the page itself is not refreshed
