### ISSUE TITLE
A blank page is opened when trying to log in to Facebook from a "Facebook Comments" field

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/contain-facebook#39]
**[Notes]:**
- Even if you are not logged in to Facebook, after following the normal log in flow, you will encounter the same issue. However, this could be encountered quite easily since we assume most of the users will be logged-in in the container.

**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Facebook Container" add-on (1.2.3) installed.
- You must be logged in to Facebook.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a website that has the "Facebook Comments" plug-in (list in Notes).
3. Click the comment field and write a string.
4. Click the "Log In to Post" button and observe the behavior.

**[Expected result]:**
- The "Log In" with Facebook window is opened.

**[Actual result]:**
- A blank page is opened in a new tab with the number 1 displayed in the top left corner.

**[Additional Notes]:**
- Here is a [list](https://docs.google.com/spreadsheets/d/1P3dm_4b4InxotumMZXFIZnZHWKEl9KbWLwz-l7hLDTY/edit#gid=0) with some websites with the "Facebook Comments" plug-in. We must mention that spotify.com, shutterstock.com, usatoday.com and nfl.com are quite known sites that use this way of commenting so this increases the bug severity.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37963540-4098621e-31c7-11e8-9b72-060713fb64e3.gif)

**Comment by SoftVision-PaulOiegas** [comment]
@pdolanjski just to be sure we fully understand this issue. If the visited website has a Facebook comments section embedded in it, the users won't be able to comment at all on the website because of this.

**Comment by TanviHacks** [comment]
Yes.

**Comment by maxxcrawford** [comment]
With the release of [2.0](https://github.com/mozilla/contain-facebook/releases/tag/2.0.0), this is has changed somewhat. Instead of having a login issue with the comments, now they're block/removed entirely. 

Without the blocker, when clicking the comment icon from the left sidebar: 
![image](https://user-images.githubusercontent.com/2692333/58981122-607b1000-8797-11e9-93fb-77ae19c6dea4.png)

With FBC running, clicking the comment icon does nothing. 

Additionally, I opened up a second issue to add share badge support to this site: #433
