### ISSUE TITLE
Explicitly assigning Facebook to Facebook Container from MAC menu will make the user end up with 2 opened Facebook tabs at each visit

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/contain-facebook#40]
**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Facebook Container" add-on (1.2.3) installed.
- Have the Firefox Multi-Account Containers add-on (6.0.0) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the https://www.facebook.com/ and click the "Multi-Account Containers" toolbar button.
3. Check the "Always open in Facebook" option and navigate to https://www.facebook.com/ in a new tab.
4. In the container confirmation tab check the "Remember my decision for this site" option.
5. Click the "Open in Facebook Container" button.
6. Open a new tab and navigate to Facebook.

**[Expected result]:**
- A single Facebook container tab is opened and the page is correctly loaded.

**[Actual result]:**
- Two Facebook container tabs are opened and the page is loaded in both.

**[Additional Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37970450-2edc88b0-31dc-11e8-8a4d-902f66aa846e.gif)

**Comment by stoically** [comment]
That's because contain-facebook only checks once for MAC assignments when initialized. One possible way to quick fix this is to check in `webRequest.onBeforeRequest` for assignments too.

Related: https://github.com/mozilla/contain-facebook/issues/23#issuecomment-376618084 https://github.com/mozilla/multi-account-containers/issues/1121#issuecomment-366522211

**Comment by SoftVision-CarmenFat** [comment]
Tested this issue with Facebook Container version 1.2.5, on Firefox Release 59.0.2, Beta 60.0b7 and Nightly 61.0a1 (2018-03-29), across platforms: Windows 10 x64, Ubuntu 14.04 x64 and macOS 10.12.6.
Although this issue is no longer reproducible, fixing it introduced a regression that @Softvision-MariusComan filed here: #77.
