### ISSUE TITLE
In-content panel enabling users to "allow FB to track me on this site"

### ISSUE THREAD

**Issue by arthur-mozilla** [mozilla/contain-facebook#422]
We have a design here:
https://mozilla.invisionapp.com/d/main#/console/17203644/365230778/preview
(Copy to be updated.)

**Comment by maxxcrawford** [comment]
Sites affected/test group: 
https://magicseaweed.com/Spain-Portugal-Surf-Forecast/8/  (#423)

**Comment by fullakingi** [comment]
+1 for the feature to disable Facebook container for certain sites. I have to login to Social media scheduling software that integrate with Facebook - have to switch to using Chrome or Opera but prefer to stay in Firefox.

**Comment by drozdowsky** [comment]
this feature is a must

**Comment by reanimus** [comment]
Uninstalling this until I can add sites into the container. It's utterly breaking my workflow and the privacy benefit isn't worth it for me.

**Comment by agrastiOs** [comment]
+1, can't use the plugin without this feature.

**Comment by rkachowski** [comment]
Certain sites are just unusable with this enabled, and the clunkiness of going to the extensions menu just to disable/reenable the feature for a specific site seriously damages the usefulness of this extension.

**Comment by DonLexos** [comment]
Greenlisting websites to add to the list of "sites allowed in facebook container" would be really helpfull especially for websites made to work with Facebook. The dashboard of ChatFuel (chatbot platform for Facebook Messenger) for example requires login and contact with Facebook, and right now there is no way to add them to the Facebook fenced container.

**Comment by mwheinz** [comment]
Add me to the list of people who need to be able to white-list sites for the facebook container. I wasted hours looking for how to do this before I realized that the "Sites you've allowed" dialog is a straight up lie...

**Comment by bhison** [comment]
having a "sites you've allowed" and no way to add to it is an outrageous anti-pattern

**Comment by xurizaemon** [comment]
Please update users on timeline for this request - the number of duplicate issues being opened on this item must be a clear signal of user demand.

If it's not actively being worked on, please let the community know so they can contribute towards it.

**Comment by brimwats** [comment]
How can we add sites to the affected list? This breaks the "get a free sample by sharing" on adagio.com. I cant figure out how to put adagio into the container

**Comment by AndrewKvalheim** [comment]
Affected: facebookincubator/RapiD#5

**Comment by R-Adrian** [comment]
+1
adding / editing the customizable site list is badly needed

**Comment by TaylorSMarks** [comment]
Hey, know what's the absolute worst design possible?
The one you already have!

You were okay with pushing this out in its completely broken state already - have somebody spend half hour to bang out a bare bones UI that's at least functional.

Now I have to go disable it entirely.

**Comment by groovecoder** [comment]
@TaylorSMarks - Thank you for speaking directly and honestly, but per [the Mozilla CPG](https://www.mozilla.org/en-US/about/governance/policies/participation/), please keep criticism respectful and positive too.

**Comment by RVAUser** [comment]
+1 on this issue.  And another +1 because of the verbiage online is promulgating false information.  E.g., "Facebook Container will block these trackers and display the fence icon to show you where trackers were removed."  FC did NOT display the fence icon on [this page](https://www.conquestgraphics.com/news/nonprofit-partners-2019/camp-hanover).  I then spent the next 90 minutes trying to figure out how to "like" this page (in order to help a non-profit win some free graphic design work), but to no avail.  
- The description of the app on the [Mozilla Add-ons page](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/) reads, "The Facebook Container extension for Firefox helps you take control and isolate your web activity from Facebook."  This is false.  I have no control at all.  This is a blunt instrument that simply disables all Facebook tracking.  The description should clearly state this.
- I also read on another support/description page (can't find it now), "You can allow other sites into the Facebook Container boundary."  This is patently false - and this is the statement that prompted me to spend an hour trying to figure out how to do so.  **PLEASE** correct the information on your various support pages to alert the user that they CANNOT allow other sites in.  Misinformation is far more damaging and hurtful than no information at all.

**Comment by alecksmart** [comment]
+1 for the issue

**Comment by jeffreyddavis** [comment]
I need this so I can test facebook on client sites without having to constantly add/remove the plugin.

**Comment by maxxcrawford** [comment]
**Happy New Year!** 

Quick update for everyone following this issue: We have a PR in progress. Expected to have it released sometime early 2020! 🎉

**Comment by tofagerl** [comment]
Great! Loving Firefox these days - loving the containers feature, and loving all the blocking stuff :D

**Comment by joshwolff1** [comment]
Any update?

**Comment by mrfifiak** [comment]
@joshwolff1 you can follow updates in #566, but there's been no info from the dev for 13 days.

**Comment by xurizaemon** [comment]
@joshwolff1 PR #566 is linked above your comment, work is in progress there. Looks promising!

**Comment by turdfergusonpdx** [comment]
Wow, the fence shows 3 greenlit sites and indicates that the user can add sites but it's not actually possible? This is weird, and makes the extension totally unusable for me.

**Comment by 0x3333** [comment]
Well, I managed to add a website to Facebook Container:

1 - Inspect the Facebook Container AddOn: about:debugging#/runtime/this-firefox
2 - Click "Inspect" in the Facebook Container
3 - Go to tab "Console" and type: addDomainToFacebookContainer("https://api.whatsapp.com")

You added https://api.whatsapp.com to the URLs in the Facebook Container, now I can use the API without Facebook Container blocking it.

**Comment by hfball** [comment]
Found a procedure to do this manually through the debug console. Mozilla reps can verify, or delete my post if this is forbidden, but it works.

1 - Inspect the Facebook Container AddOn: about:debugging#/runtime/this-firefox
2 - Click "Inspect" in the Facebook Container
3 - Go to tab "Console" and type: addDomainToFacebookContainer("https://api.whatsapp.com")

You added https://api.whatsapp.com to the URLs in the Facebook Container, now you can use 
the API without Facebook Container blocking it.

**Comment by 0x3333** [comment]
@hfball I posted here this workaround 8 days ago... 😂😂😂

Works, but too cumbersome, real support in the UI would be great!

**Comment by hfball** [comment]
What? You expect me to read _all_ the posts? I spend most of my time on 
Usenet. That never happens. 😂

Yeah. It sucks, but I got my social media console app working with it. I 
probably even read your post to do it, because I'm a very silly person.

**Comment by maxxcrawford** [comment]
The newest version of the add-on has been released – which has this feature in it. It should update automatically on its on, but if you'd like to speed that process up: 

- Go to `about:addons`
- Click the Gear icon
- Select "Check for Updates" 

<img width="339" alt="image" src="https://user-images.githubusercontent.com/2692333/76077701-d995d680-5f66-11ea-8cb4-8739d9a7b05d.png">

--- 

To **add** a site to the Facebook Container, open the panel on whichever page you wish to include, and click "Allow site in Facebook Container" button. First, it will confirm this action and then add it and reload the page. _Note that `about:` system pages cannot be added_. 

![image](https://user-images.githubusercontent.com/2692333/74570315-f891e180-4f41-11ea-8523-a3e22e647861.png)

To **remove** a site from the Facebook Container, you can do the inverse, by navigating to a page within the Facebook Container<sup>*</sup>, open the panel and click: 

![image](https://user-images.githubusercontent.com/2692333/74570952-c92fa480-4f42-11ea-99ee-b88578d934dc.png)

Additionally, you can manage all the custom sites that have been added by clicking on "Sites Allowed in Facebook Container".  _Note that [Facebook-owned domains](https://github.com/mozilla/contain-facebook/blob/master/src/background.js#L7-L23)_ cannot be removed. 

![image](https://user-images.githubusercontent.com/2692333/74570327-fc256880-4f41-11ea-9ef3-d96786e949d3.png)

**Comment by Fizzie41** [comment]
Hi. Am I right in thinking that this problem is still occurring?

I'm trying to work on https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.47/-28.07261/153.43373, but it won't allow me to save my changes, apparently due to Facebook Container?

The instructions above say:
"To add a site to the Facebook Container, open the panel on whichever page you wish to include, and click "Allow site in Facebook Container" button. First, it will confirm this action and then add it and reload the page."
but when I click on the Container icon, I only have the options to see "How Container works" & "Sites allowed in Container", together with a greyed out "Remove site from Container" button.

There is no option to add a site?
