### ISSUE TITLE
Disable add-ons on specific sites

### ISSUE THREAD

**Issue by Grinvind** [mozilla/contain-facebook#437]
Good day! How do I add sites I need to exceptions? Thanks

**Comment by maxxcrawford** [comment]
It is currently dependent if a site you want to add to the Facebook Container has a "Login with Facebook" button that also has a badge. (See screenshot below)

Unfortunately, if a site you want to add does not have the specific login detection, there is no way to add it on a site-by-site basis. We're working on a feature currently for it. You can track progress on this issue here: #422  

Example: https://imgur.com/signin 

![image](https://user-images.githubusercontent.com/2692333/59215077-f7700f80-8b7d-11e9-93fe-44b583597eac.png)
