### ISSUE TITLE
Wit.ai not working

### ISSUE THREAD

**Issue by fvildoso** [mozilla/contain-facebook#440]
Hi guys,

The container produces this on Wit.ai 
![imagen](https://user-images.githubusercontent.com/9140883/59208473-25058a80-8b77-11e9-88fc-7e883ef24ed8.png)

And the browser console says
`ReferenceError: requireLazy is not definedwit.ai:20:1 <anónima> https://wit.ai/:20`

Regards.

**Comment by maxxcrawford** [comment]
This add-on blocks all Facebook resources for any site outside of the Facebook container, [including CDN assets](https://github.com/mozilla/contain-facebook/blob/65f5a1ac420b6579ce4a311f30838cd0adca8507/src/background.js#L9). (`https://static.xx.fbcdn.net`). This site will not function as is, but this is expected behavior. 

We're currently discussing CDN-specific resources to be loaded outside of the container, but it's not attached to any specific release right now. Leaving this issue open for visibility. Thanks for reporting this issue!

**Comment by blandinw** [comment]
@maxxcrawford while I understand this is expected for now, is there a workaround available today?

**Comment by warnak** [comment]
Hi, it is going to be an year since this issue, is there a status update? (just bumping this back)

**Comment by maxxcrawford** [comment]
@warnak Yeah! Simply [add this site to the Facebook Container](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md) to load the blocked resources. This issue should've been marked resolved with the last release.
