### ISSUE TITLE
handle not facebook.com domains

### ISSUE THREAD

**Issue by bhuettmann** [mozilla/contain-facebook#49]
at the moment also https://deletefacebook.com/ get containerized.
That's no big issue, but looks od.

if i read the code right its line 5 in https://github.com/mozilla/contain-facebook/blob/master/background.js where the domains are detailed.

**Comment by stoically** [comment]
The fix for that is available in https://github.com/mozilla/contain-facebook/pull/44

**Comment by bhuettmann** [comment]
Thank you :-)

**Comment by bhuettmann** [comment]
Sorry, but even with 1.2.4 all domains ending on facebook.com get containerized:
![fb-container20180328a](https://user-images.githubusercontent.com/30300530/38028119-2b60773a-3292-11e8-99da-4304acf2f18a.png)
maybe its in the reg-expression.

**Comment by Perflyst** [comment]
@bhuettmann the pull request has not yet been merged, so nothing has been changed in the domains.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible using Facebook Container (v1.2.5) on latest Firefox Release 59.0.2 (both official version and unbranded one). Tested on Windows 7 x64, Mac 10.13.3 and Ubuntu 14.04 x64. 
In order to test this issue I have used the following pages:
- https://deletefacebook.com/
- http://www.downfacebook.com/

**Comment by bhuettmann** [comment]
\o/ its fixed!
Thank you
