### ISSUE TITLE
Log in with Facebook still works

### ISSUE THREAD

**Issue by Suleman-Elahi** [mozilla/contain-facebook#57]
While clicking on Log in or Sign up with Facebook take you to the Facebook container. Ideally, it shouldn't do that. It must take you outside the container.
![free mouse auto clicker software to auto click in minimized windows](https://user-images.githubusercontent.com/24384996/38012575-e3319dd4-3216-11e8-9409-75f02d56df27.gif)

**Comment by ericBG** [comment]
Why shouldn't it go to the container? It's facebook activity and should be contained, no?

**Comment by Perflyst** [comment]
If you log in via Facebook, Facebook places a cookie in your no container. This tracks you with your logged in account. It's even easier for you if he opens it in the Facebook container because you don't have to log in again.

**Comment by lopis** [comment]
Any webpage where you need to login with facebook must also be inside the facebook container. Otherwise, what is the point of using containers?

**Comment by Perflyst** [comment]
Good point! That is a problem...
To your question, containers keep cookies, local storage, dome storage and what else belongs separate from each other. So you can use several accounts on the same platform and you are more protected against tracking.

**Comment by Perflyst** [comment]
@Suleman-Elahi Take a look at the README, it is explained there: https://github.com/mozilla/contain-facebook/blob/master/README.md#logging-in-or-creating-accounts-on-other-websites-using-facebook

**Comment by pauljt** [comment]
The facebook login flow will still work only when it doesn't rely at all on cookies - i.e. if it uses URL tokens. Spotify for example still seems to work, despite NOT being in the Facebook container. Facebook requests from Spotify pages will not see your facebook cookie from your facebook container, but the login flow still works since tokens are passed via URL. 

We've made a design decision here to allow linking to and from the facebook container. While there is a non-zero risk that URL links could contain tracking data, if you break links, it breaks the user experience, and defeats the main goal of this addon (which is still to allow Facebook to be usable).

**Comment by pauljt** [comment]
Im going to close this since I think this is working as in intended.
