### ISSUE TITLE
Update this addon to isolate more social networks

### ISSUE THREAD

**Issue by Perflyst** [mozilla/contain-facebook#58]
I think it would make sense to refer this addon not only to Facebook but to the biggest other social networks. Not only Facebook tracks a lot of third party cookies, almost all of them do.

The idea behind it: Put the biggest social networks into different containers and thus help the masses relatively easily not to be tracked everywhere. It should remain as simple as possible so as not to discourage any users. No cumbersome settings, but easy to install and directly usable.

Thanks @stoically for this idea. He found the name "contain-trackers" interesting, but I think "contain-social" fits better here, because tracking and analysis services like google analytics or Matomo (formerly piwik) are only isolated if you use containers everywhere.

There is currently an [addon](https://github.com/kintesh/containerise) that works similarly, but the user has to configure everything there himself. This discourages the layman, who is in the foreground here, quite a bit. A preconfigured addon is easier.

I made a [new branch in my fork](https://github.com/Perflyst/contain-facebook/tree/contain-social) and added Google roughly but ugly. However, it works fundamentally. You can test this with [loading an addon temporary](https://blog.mozilla.org/addons/2015/12/23/loading-temporary-add-ons/).

**Comment by ocdtrekkie** [comment]
I came here just to ask Mozilla to consider making a "Google Container" extension. The auto-management of this container via an individual extension is quite handy, and removes the cognitive load of setting up your own containers.

I'd recommend it being a *separate* extension though, so that it doesn't need to have configuration, and a user can pick and choose which services they wish to throw in container-based prison.

**Comment by TanviHacks** [comment]
For now, we are not doing this.  Out of scope.
