### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by siffegh** [mozilla/contain-facebook#624]
- Facebook Container Version: 2.1.0
- Operating System + Version: Win7 Pro SP1
- Firefox Version: 74.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: None

### Actual behavior
https://socialfixer.com/download?all&fbclid=IwAR1Qw5qk-2JCkxr_vSNvuju5e-Lgilnl8K274fZ4SYszOWJJeDWKAuK-MZI#userscript  goes to the top of the page.

### Expected behavior
https://socialfixer.com/download?all&fbclid=IwAR1Qw5qk-2JCkxr_vSNvuju5e-Lgilnl8K274fZ4SYszOWJJeDWKAuK-MZI#userscript should go directly to the userscript download page, which you can get to by clicking the 'view all download options' link.

### Steps to reproduce
1. Go to mentioned link with FB container enabled > log out of FB > disable FB Container > log into FB >go to mentioned link.

**Comment by filbo** [comment]
By the time it arrives at `socialfixer.com`, it appears to somehow have rendered the URL as:

`https://socialfixer.com/download?all=#userscript`

This link does not work; it must be:

`https://socialfixer.com/download?all#userscript`

(without added '=').  The destination site is probably mis-parsing its URL query data -- but at the same time, FB container should not be mutating it like that.

**Comment by maxxcrawford** [comment]
I'm not seeing any blocking from the Facebook Container to https://socialfixer.com/download#userscript at all. Where was the [original link](https://socialfixer.com/download?all&fbclid=IwAR1Qw5qk-2JCkxr_vSNvuju5e-Lgilnl8K274fZ4SYszOWJJeDWKAuK-MZI#userscript) found? On Facebook?

**Comment by filbo** [comment]
Ed: is this still happening with current FF & FB container?

Max: this was not a matter of blocking, but of bad link parsing / editing.  The links shown in Ed's original post are as-generated by FB when clicking out of an FB page.  That is:

A user's comment on FB mentions the URL:

(1) https://socialfixer.com/download?all#userscript

When another user clicks that link, FB actually direct them to:

https://socialfixer.com/download?all&fbclid=IwAR1Qw5qk-2JCkxr_vSNvuju5e-Lgilnl8K274fZ4SYszOWJJeDWKAuK-MZI#userscript 

(where the 'fbclid' is an ephemeral value).  This can be looked at as:

(2) https://socialfixer.com/download?all&fbclid=gibberish#userscript

The target page has zero interest in any 'fbclid' parameter, it's just some junk that FB add (would perhaps be of interest to an FB advertising partner, but not to this particular targeted page).

The **problem** is (or was) that after clicking through that link, the user actually ended up on:

(3) https://socialfixer.com/download?all=&fbclid=gibberish#userscript

Note the added '=' between 'all' and '&'.  This happens with FB Container, and not without it, so it seems to be a problem with FB Container parsing URL parameters and incorrectly adding '=' to parameters without an attached value.

If you will follow links (1) and (2) above, you should see identical results; this is as expected.  You see a Social Fixer downloads page which shows 'all' available downloads.

If you follow (3), you'll see a browser-specific page; if you've opened it with FF, this page will list only the FF and userscript editions of Social Fixer.  This is not as intended; the parameter 'all' was supposed to be received, parsed, and cause the target page to display all possible downloads.

====

To _understand_ the issue, you must visit the 3 links above and observe the different results.

To _reproduce_ the issue, you must click through a Facebook post which, when posted, contained a link identical to (1).  You can make this post yourself (for instance).  Make an FB post with that link (set audience to 'Only me' so nobody else sees it).  Mouse over the link in the rendered post: you should observe a URL of form (2), i.e. (1) with added '?fbclid=gibberish'.  Click through it and you **should** arrive at the same form (2) URL.  **If** you are using FF + FB Container, and if the bug is still present, you will instead see form (3) (and the resulting page lacks all-browser downloads).

You should be able to reproduce the same issue with any external (to FB) link posted on FB, with a '?' URL parameter which doesn't have an '=value' portion.  i.e. if your post said `foo.bar.com?parm1&parm2=foo`, I'd expect FB to render it as `foo.bar.com?parm1&parm2=foo&fbclid=gibberish`; and then, if the bug is still present, _clicking_ the link would lead to `foo.bar.com?parm1!!=!!&parm2=foo&fbclid=gibberish` -- with an added '=' after 'parm1'.  OR, a fragment indicator '#frag' at the end of the posted URL might be a necessary part of the failure condition.

====

I don't use FB Container so this is only my analysis of what Ed and other users reported, after I directed them to carefully observe specific things.  This is why I write in terms of '_if_ the bug is still present', and don't have most specific details about whether '#frag' is a necessary condition.

To me, the bug is 'I can't direct our users to this specific link because some of them end up in the wrong place'.  Our 'download.html' page could, probably should, simply be updated to understand 'all=' the same as 'all'.  But that would sweep under the rug that the parameter was being mis-edited, leaving other target sites to suffer the same problem -- sites which would not have a detailist like me to figure out what was actually triggering the problem.

**Comment by maxxcrawford** [comment]
Got'cha. Thanks for the deep dive on this. As this is more of an issue with Facebook itself amending links and not this extension, I'm gonna mark this as resolved.

**Comment by filbo** [comment]
It is **NOT** an issue with FB, but with FB Container.  This is a false closure.

FB issue a working URL.  FB Container edits it to a broken URL.  How is that an FB issue?
