### ISSUE TITLE
Contain facebook doesn't work with workplace.com

### ISSUE THREAD

**Issue by kloneets** [mozilla/contain-facebook#672]
We use facebook's workplace with custom company's authentication and contain-facebook either blocks saml.php functionality or strips some necessary data on login. Therefore I get 404 This page isn't available.

- Facebook Container Version: 2.1.1
- Operating System + Version: Ubuntu 20.04.1 LTS
- Firefox Version: 79.0 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Amazon Assistant	extension	10.2008.6.11904	true	abb@amazon.com
Amazon.com	extension	1.1	true	amazondotcom@search.mozilla.org
Bing	extension	1.1	true	bing@search.mozilla.org
DuckDuckGo	extension	1.0	true	ddg@search.mozilla.org
eBay	extension	1.1	true	ebay@search.mozilla.org
Facebook Container	extension	2.1.1	true	@contain-facebook
GNOME Shell integration	extension	10.1	true	chrome-gnome-shell@gnome.org
Google	extension	1.0	true	google@search.mozilla.org
JetBrains Toolbox Extension	extension	1.17.7265	true	{bf9e77ee-c405-4dd7-9bed-2f55e448d19a}
WebSocketSniff	extension	0.2.1	true	hello@hellosite.org
Wikipedia (en)	extension	1.0	true	wikipedia@search.mozilla.org
English (CA) Language Pack	locale	79.0buildid20200720193547	true	langpack-en-CA@firefox.mozilla.org
English (GB) Language Pack	locale	79.0buildid20200720193547	true	langpack-en-GB@firefox.mozilla.org

### Actual behavior
Go to <my-company>.facebook.com, try to login -> redirect to conpany's login page -> redirect to <my-company>.facebook.com/work/saml.php which gives 404 page not found.

### Expected behavior
Go to <my-company>.facebook.com, try to login -> redirect to conpany's login page -> redirect to <my-company>.facebook.com with valid session.

### Steps to reproduce
1. Go to <my-company>.facebook.com
2. Login (this step automatically redirects to companies inner login system)
3. Get redirect to logged in workplace

**Comment by maxxcrawford** [comment]
You'll need to add your company domain (that it redirects to for authentication) to the Facebook Container. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). Please reopen this if adding the site doesn't get your issue resolved. Thanks!

**Comment by 211217613** [comment]
Any possibility that we can remove workplace domain from the facebook container?

I have my corporate links open in a "work" container so when I go from workplace to my company's login page the firefox multi-container tabs go into an endless loop of redirection.

**Comment by rimas-kudelis** [comment]
Please consider reopening this issue.

I have the Google container extension installed next to Facebook container, and the organization uses Google for SSO, which means I would have to add google.com to Facebook domains, which then conflicts with the Google container and causes any google.com page that is being loaded to jump between Facebook and Google containers in an infinite loop.

For now, I worked it around by temporarily disabling Google Container, then adding google.com to Facebook Container's list, successfully logging in to Workplace, then removing google.com from Facebook Container's list and reenabling the Google Container plugin. It's not something I'd want to go through again though.

Is it really impossible to make a jump between Facebook container/no container/any other container seamless and without data loss? I find it weird, because I believe I can log in to any other service via Google without such hiccups.
