### ISSUE TITLE
Wiping cookies when we add new domains

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/contain-facebook#80]
Should we wipe facebook.com cookies again, forcing users to relogin to facebook in their container, when we update to 1.3.0 and add messenger.com and other facebook domains to the Facebook Container?  

Here's why - consider the following scenario

1) User installs facebook containers 1.2.5 or previous
2) facebook cookies wiped
3) user visits messenger.com in regular container.  They are still logged in (or they relogin).
4) messenger.com embeds facebook.com subresource.
5) facebook.com sets a cookie that ties you to your user identity that it learned from messenger.com (via url params, post message, or something else)
6) user gets updated to 1.3.0
7) messenger.com cookies get deleted
8) facebook.com cookies still exist in default container and can track the user.

If we do this though, we may want to communicate that this is a breaking update that will make you login again.

Labeling 1.3.0 until we decide if we need this or not.

**Comment by stoically** [comment]
All cookies in the default container for all `FACEBOOK_DOMAINS` are cleared on every initialization of the Add-on (which also happens on install or update). So from my understanding this scenario is already covered since the facebook subresource cookie from messenger is set in the default container.

https://github.com/mozilla/contain-facebook/blob/a13f525de96b67db071c2a0e9d72b3cf7757700a/background.js#L199-L203

Like @SoftVision-PaulOiegas stated in https://github.com/mozilla/contain-facebook/issues/74#issuecomment-377510911, reports that Facebook cookies still end up in the default container might be because of #61: In this case the initialization happens on startup, cookies are cleared, and *after* that loads facebook in the default container and sets cookies, since the request/tab could not get correctly canceled/reopened. Or it's simply because facebook cookies can still be set from subresources in general in all containers. Personally I'd say https://github.com/mozilla/contain-facebook/issues/74#issuecomment-377586113 is the way to go by preventing Facebook cookies from ever *leaving* the browser if it's not a Facebook Container.

**Comment by TanviHacks** [comment]
@stoically so essentially, we need a PR that does a loop over all non-Facebook contexts within 
function clearFacebookCookies ()?

**Comment by stoically** [comment]
@TanviHacks If we want to clear for all containers except the Facebook Container then that would be the way to go regarding initial wiping, yep.

**Comment by TanviHacks** [comment]
Yes, lets wipe from all containers except the Facebook Container.
