### ISSUE TITLE
Facebook Container 2.3.3 causes font size change

### ISSUE THREAD

**Issue by andyross63** [mozilla/contain-facebook#865]
I use Netvibes.com in 'apps' mode as my home page. Suddenly, the font size used for the news headlines increased. After some trial and error, I figured out it wsa Facebook Container 2.3.3. Another computer that was still on 2.3.2 has no issue. If I turn Facebook container off on the 2.3.3 computer, the font is fine. The change happens instantly when turned on and off.
FBC Off:
![FBCOff](https://user-images.githubusercontent.com/33353167/189149342-ccf61095-3db1-4709-9f2a-93da2c90d198.jpg)

FBC On:
![FBCOn](https://user-images.githubusercontent.com/33353167/189149376-ef392b37-b767-44fc-9c7d-e97537be1d91.jpg)

**Comment by aaronsantiago** [comment]
#866 related

**Comment by andyross63** [comment]
Appears to be fixed in the quickly released 2.3.4.

**Comment by Siedlerchr** [comment]
Can confirm is fixed  2.3.4. You need to remove the addon and readd it to get the new version

**Comment by willdurand** [comment]
> Can confirm is fixed 2.3.4. You need to remove the addon and readd it to get the new version

A slightly better alternative would be to "Check for updates" in `about:addons` > Extensions:

![Screenshot 2022-09-08 at 19 46 23](https://user-images.githubusercontent.com/217628/189190945-e2e75a53-9225-408b-b7b2-167d0b96867f.png)

**Comment by groovecoder** [comment]
Thanks everyone for the quick feedback on this. We will be more diligent about testing website compatibility in the future.

90K users received the buggy 2.3.3 version, and now 109K users are on the latest 2.3.4 (i.e., the rollback) version. 1.1M users are still on 2.3.2, but their next update should jump them straight to 2.3.4 instead of the buggy 2.3.3.

We are working on a full fix to include the security improvements, performance improvements, AND the bug-fix for the styling issue.
