### ISSUE TITLE
A Facebook Container? No. Remove Referer, Enforce Content-Security-Policy and disallow mixed content.

### ISSUE THREAD

**Issue by metadings** [mozilla/contain-facebook#91]
I currently use µMatrix, just to be sure.

Look, I don't want just a Facebook Container.

I do want you to enforce the HTTP header Content-Security-Policy, by removing the star *, so no one is allowed but the same and explicitly allowed domains - and

I do want you to remove the Referer HTTP Header. Just do this. It's not that hard. You can do so already by setting network.http.sendRefererHeader = 0 (no referer at all).

Finally, I do want you to disallow "mixed content" - not even for css/images (security.mixed_content.block_display_content = true).

**Comment by stoically** [comment]
> I do want you to enforce the HTTP header Content-Security-Policy, by removing the star *, so no one is allowed but the same and explicitly allowed domains - and

Enforcing [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) for sites in general isn't in the scope of this Add-on. Changing it just for facebook isn't necessary since Facebook is in a container and by that already protected regarding XSS in a similar fashion.

> I do want you to remove the Referer HTTP Header

Navigating to Facebook URLs from the default container and Navigating to Non-Facebook URLs in the Facebook container will already remove the Referer Header due to canceling request and reopening of the tab.

> Finally, I do want you to disallow "mixed content" - not even for css/images (security.mixed_content.block_display_content = true).

Add-ons can't change that configuration.
